// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReadFileFS creates a new instance of MockReadFileFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadFileFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadFileFS {
	mock := &MockReadFileFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadFileFS is an autogenerated mock type for the ReadFileFS type
type MockReadFileFS struct {
	mock.Mock
}

type MockReadFileFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadFileFS) EXPECT() *MockReadFileFS_Expecter {
	return &MockReadFileFS_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockReadFileFS
func (_mock *MockReadFileFS) Open(name string) (fs.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadFileFS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockReadFileFS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockReadFileFS_Expecter) Open(name interface{}) *MockReadFileFS_Open_Call {
	return &MockReadFileFS_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockReadFileFS_Open_Call) Run(run func(name string)) *MockReadFileFS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadFileFS_Open_Call) Return(file fs.File, err error) *MockReadFileFS_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockReadFileFS_Open_Call) RunAndReturn(run func(name string) (fs.File, error)) *MockReadFileFS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockReadFileFS
func (_mock *MockReadFileFS) ReadFile(name string) ([]byte, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadFileFS_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockReadFileFS_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name string
func (_e *MockReadFileFS_Expecter) ReadFile(name interface{}) *MockReadFileFS_ReadFile_Call {
	return &MockReadFileFS_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *MockReadFileFS_ReadFile_Call) Run(run func(name string)) *MockReadFileFS_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadFileFS_ReadFile_Call) Return(bytes []byte, err error) *MockReadFileFS_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReadFileFS_ReadFile_Call) RunAndReturn(run func(name string) ([]byte, error)) *MockReadFileFS_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}
