// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSubFS creates a new instance of MockSubFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubFS {
	mock := &MockSubFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubFS is an autogenerated mock type for the SubFS type
type MockSubFS struct {
	mock.Mock
}

type MockSubFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubFS) EXPECT() *MockSubFS_Expecter {
	return &MockSubFS_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockSubFS
func (_mock *MockSubFS) Open(name string) (fs.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubFS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockSubFS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockSubFS_Expecter) Open(name interface{}) *MockSubFS_Open_Call {
	return &MockSubFS_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockSubFS_Open_Call) Run(run func(name string)) *MockSubFS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubFS_Open_Call) Return(file fs.File, err error) *MockSubFS_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockSubFS_Open_Call) RunAndReturn(run func(name string) (fs.File, error)) *MockSubFS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Sub provides a mock function for the type MockSubFS
func (_mock *MockSubFS) Sub(dir string) (fs.FS, error) {
	ret := _mock.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for Sub")
	}

	var r0 fs.FS
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.FS, error)); ok {
		return returnFunc(dir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.FS); ok {
		r0 = returnFunc(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FS)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubFS_Sub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sub'
type MockSubFS_Sub_Call struct {
	*mock.Call
}

// Sub is a helper method to define mock.On call
//   - dir string
func (_e *MockSubFS_Expecter) Sub(dir interface{}) *MockSubFS_Sub_Call {
	return &MockSubFS_Sub_Call{Call: _e.mock.On("Sub", dir)}
}

func (_c *MockSubFS_Sub_Call) Run(run func(dir string)) *MockSubFS_Sub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubFS_Sub_Call) Return(fS fs.FS, err error) *MockSubFS_Sub_Call {
	_c.Call.Return(fS, err)
	return _c
}

func (_c *MockSubFS_Sub_Call) RunAndReturn(run func(dir string) (fs.FS, error)) *MockSubFS_Sub_Call {
	_c.Call.Return(run)
	return _c
}
