// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStatFS creates a new instance of MockStatFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatFS {
	mock := &MockStatFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatFS is an autogenerated mock type for the StatFS type
type MockStatFS struct {
	mock.Mock
}

type MockStatFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatFS) EXPECT() *MockStatFS_Expecter {
	return &MockStatFS_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockStatFS
func (_mock *MockStatFS) Open(name string) (fs.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatFS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockStatFS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockStatFS_Expecter) Open(name interface{}) *MockStatFS_Open_Call {
	return &MockStatFS_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockStatFS_Open_Call) Run(run func(name string)) *MockStatFS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatFS_Open_Call) Return(file fs.File, err error) *MockStatFS_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockStatFS_Open_Call) RunAndReturn(run func(name string) (fs.File, error)) *MockStatFS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockStatFS
func (_mock *MockStatFS) Stat(name string) (fs.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatFS_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockStatFS_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *MockStatFS_Expecter) Stat(name interface{}) *MockStatFS_Stat_Call {
	return &MockStatFS_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *MockStatFS_Stat_Call) Run(run func(name string)) *MockStatFS_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatFS_Stat_Call) Return(fileInfo fs.FileInfo, err error) *MockStatFS_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockStatFS_Stat_Call) RunAndReturn(run func(name string) (fs.FileInfo, error)) *MockStatFS_Stat_Call {
	_c.Call.Return(run)
	return _c
}
