// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReadLinkFS creates a new instance of MockReadLinkFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadLinkFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadLinkFS {
	mock := &MockReadLinkFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadLinkFS is an autogenerated mock type for the ReadLinkFS type
type MockReadLinkFS struct {
	mock.Mock
}

type MockReadLinkFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadLinkFS) EXPECT() *MockReadLinkFS_Expecter {
	return &MockReadLinkFS_Expecter{mock: &_m.Mock}
}

// Lstat provides a mock function for the type MockReadLinkFS
func (_mock *MockReadLinkFS) Lstat(name string) (fs.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Lstat")
	}

	var r0 fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadLinkFS_Lstat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lstat'
type MockReadLinkFS_Lstat_Call struct {
	*mock.Call
}

// Lstat is a helper method to define mock.On call
//   - name string
func (_e *MockReadLinkFS_Expecter) Lstat(name interface{}) *MockReadLinkFS_Lstat_Call {
	return &MockReadLinkFS_Lstat_Call{Call: _e.mock.On("Lstat", name)}
}

func (_c *MockReadLinkFS_Lstat_Call) Run(run func(name string)) *MockReadLinkFS_Lstat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadLinkFS_Lstat_Call) Return(fileInfo fs.FileInfo, err error) *MockReadLinkFS_Lstat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockReadLinkFS_Lstat_Call) RunAndReturn(run func(name string) (fs.FileInfo, error)) *MockReadLinkFS_Lstat_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockReadLinkFS
func (_mock *MockReadLinkFS) Open(name string) (fs.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadLinkFS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockReadLinkFS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockReadLinkFS_Expecter) Open(name interface{}) *MockReadLinkFS_Open_Call {
	return &MockReadLinkFS_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockReadLinkFS_Open_Call) Run(run func(name string)) *MockReadLinkFS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadLinkFS_Open_Call) Return(file fs.File, err error) *MockReadLinkFS_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockReadLinkFS_Open_Call) RunAndReturn(run func(name string) (fs.File, error)) *MockReadLinkFS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// ReadLink provides a mock function for the type MockReadLinkFS
func (_mock *MockReadLinkFS) ReadLink(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadLink")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadLinkFS_ReadLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadLink'
type MockReadLinkFS_ReadLink_Call struct {
	*mock.Call
}

// ReadLink is a helper method to define mock.On call
//   - name string
func (_e *MockReadLinkFS_Expecter) ReadLink(name interface{}) *MockReadLinkFS_ReadLink_Call {
	return &MockReadLinkFS_ReadLink_Call{Call: _e.mock.On("ReadLink", name)}
}

func (_c *MockReadLinkFS_ReadLink_Call) Run(run func(name string)) *MockReadLinkFS_ReadLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadLinkFS_ReadLink_Call) Return(s string, err error) *MockReadLinkFS_ReadLink_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockReadLinkFS_ReadLink_Call) RunAndReturn(run func(name string) (string, error)) *MockReadLinkFS_ReadLink_Call {
	_c.Call.Return(run)
	return _c
}
