// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReadDirFS creates a new instance of MockReadDirFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadDirFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadDirFS {
	mock := &MockReadDirFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadDirFS is an autogenerated mock type for the ReadDirFS type
type MockReadDirFS struct {
	mock.Mock
}

type MockReadDirFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadDirFS) EXPECT() *MockReadDirFS_Expecter {
	return &MockReadDirFS_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockReadDirFS
func (_mock *MockReadDirFS) Open(name string) (fs.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadDirFS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockReadDirFS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockReadDirFS_Expecter) Open(name interface{}) *MockReadDirFS_Open_Call {
	return &MockReadDirFS_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockReadDirFS_Open_Call) Run(run func(name string)) *MockReadDirFS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadDirFS_Open_Call) Return(file fs.File, err error) *MockReadDirFS_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockReadDirFS_Open_Call) RunAndReturn(run func(name string) (fs.File, error)) *MockReadDirFS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type MockReadDirFS
func (_mock *MockReadDirFS) ReadDir(name string) ([]fs.DirEntry, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]fs.DirEntry, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadDirFS_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockReadDirFS_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *MockReadDirFS_Expecter) ReadDir(name interface{}) *MockReadDirFS_ReadDir_Call {
	return &MockReadDirFS_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *MockReadDirFS_ReadDir_Call) Run(run func(name string)) *MockReadDirFS_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadDirFS_ReadDir_Call) Return(dirEntrys []fs.DirEntry, err error) *MockReadDirFS_ReadDir_Call {
	_c.Call.Return(dirEntrys, err)
	return _c
}

func (_c *MockReadDirFS_ReadDir_Call) RunAndReturn(run func(name string) ([]fs.DirEntry, error)) *MockReadDirFS_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}
