// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGlobFS creates a new instance of MockGlobFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGlobFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGlobFS {
	mock := &MockGlobFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGlobFS is an autogenerated mock type for the GlobFS type
type MockGlobFS struct {
	mock.Mock
}

type MockGlobFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGlobFS) EXPECT() *MockGlobFS_Expecter {
	return &MockGlobFS_Expecter{mock: &_m.Mock}
}

// Glob provides a mock function for the type MockGlobFS
func (_mock *MockGlobFS) Glob(pattern string) ([]string, error) {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for Glob")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGlobFS_Glob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Glob'
type MockGlobFS_Glob_Call struct {
	*mock.Call
}

// Glob is a helper method to define mock.On call
//   - pattern string
func (_e *MockGlobFS_Expecter) Glob(pattern interface{}) *MockGlobFS_Glob_Call {
	return &MockGlobFS_Glob_Call{Call: _e.mock.On("Glob", pattern)}
}

func (_c *MockGlobFS_Glob_Call) Run(run func(pattern string)) *MockGlobFS_Glob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGlobFS_Glob_Call) Return(strings []string, err error) *MockGlobFS_Glob_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGlobFS_Glob_Call) RunAndReturn(run func(pattern string) ([]string, error)) *MockGlobFS_Glob_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockGlobFS
func (_mock *MockGlobFS) Open(name string) (fs.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGlobFS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockGlobFS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockGlobFS_Expecter) Open(name interface{}) *MockGlobFS_Open_Call {
	return &MockGlobFS_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockGlobFS_Open_Call) Run(run func(name string)) *MockGlobFS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGlobFS_Open_Call) Return(file fs.File, err error) *MockGlobFS_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockGlobFS_Open_Call) RunAndReturn(run func(name string) (fs.File, error)) *MockGlobFS_Open_Call {
	_c.Call.Return(run)
	return _c
}
