// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReadDirFile creates a new instance of MockReadDirFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadDirFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadDirFile {
	mock := &MockReadDirFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadDirFile is an autogenerated mock type for the ReadDirFile type
type MockReadDirFile struct {
	mock.Mock
}

type MockReadDirFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadDirFile) EXPECT() *MockReadDirFile_Expecter {
	return &MockReadDirFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockReadDirFile
func (_mock *MockReadDirFile) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReadDirFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReadDirFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockReadDirFile_Expecter) Close() *MockReadDirFile_Close_Call {
	return &MockReadDirFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockReadDirFile_Close_Call) Run(run func()) *MockReadDirFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadDirFile_Close_Call) Return(err error) *MockReadDirFile_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReadDirFile_Close_Call) RunAndReturn(run func() error) *MockReadDirFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockReadDirFile
func (_mock *MockReadDirFile) Read(bytes []byte) (int, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadDirFile_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockReadDirFile_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - bytes []byte
func (_e *MockReadDirFile_Expecter) Read(bytes interface{}) *MockReadDirFile_Read_Call {
	return &MockReadDirFile_Read_Call{Call: _e.mock.On("Read", bytes)}
}

func (_c *MockReadDirFile_Read_Call) Run(run func(bytes []byte)) *MockReadDirFile_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadDirFile_Read_Call) Return(n int, err error) *MockReadDirFile_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockReadDirFile_Read_Call) RunAndReturn(run func(bytes []byte) (int, error)) *MockReadDirFile_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type MockReadDirFile
func (_mock *MockReadDirFile) ReadDir(n int) ([]fs.DirEntry, error) {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]fs.DirEntry, error)); ok {
		return returnFunc(n)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []fs.DirEntry); ok {
		r0 = returnFunc(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadDirFile_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockReadDirFile_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - n int
func (_e *MockReadDirFile_Expecter) ReadDir(n interface{}) *MockReadDirFile_ReadDir_Call {
	return &MockReadDirFile_ReadDir_Call{Call: _e.mock.On("ReadDir", n)}
}

func (_c *MockReadDirFile_ReadDir_Call) Run(run func(n int)) *MockReadDirFile_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadDirFile_ReadDir_Call) Return(dirEntrys []fs.DirEntry, err error) *MockReadDirFile_ReadDir_Call {
	_c.Call.Return(dirEntrys, err)
	return _c
}

func (_c *MockReadDirFile_ReadDir_Call) RunAndReturn(run func(n int) ([]fs.DirEntry, error)) *MockReadDirFile_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockReadDirFile
func (_mock *MockReadDirFile) Stat() (fs.FileInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (fs.FileInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() fs.FileInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadDirFile_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockReadDirFile_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
func (_e *MockReadDirFile_Expecter) Stat() *MockReadDirFile_Stat_Call {
	return &MockReadDirFile_Stat_Call{Call: _e.mock.On("Stat")}
}

func (_c *MockReadDirFile_Stat_Call) Run(run func()) *MockReadDirFile_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadDirFile_Stat_Call) Return(fileInfo fs.FileInfo, err error) *MockReadDirFile_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockReadDirFile_Stat_Call) RunAndReturn(run func() (fs.FileInfo, error)) *MockReadDirFile_Stat_Call {
	_c.Call.Return(run)
	return _c
}
